* NAIS NIX ACTION

Nais Nix Action is a convention-over-configuration github workflow
action. You provide a flake and Nais Nix Action does the right thing!

** Conventions

You can supply the following packages or outputs and the right thing
will happen

- image -> if this attr exists and builds a docker container using
  dockerTools then we will upload the container to GAR, with some
  additonal tags

- checks, we run nix flake check, it runs all the checks outputs
  before anything else is built. If you're running on kvm (Public
  repos) or on large runners then you can run vmtests for x86_64-linux

- sbom -> if this attr exists and builds an sbom in the cyclonedx
  format then that will be uploaded to nais dependencytrack

- spec -> Is for the nais spec, if you have this output It will be built
  and uploaded to the action as spec.yaml. Then you can download that and
  use it in lieue of having a yaml file in the repo. I.e if you want to
  use any other tool to generate your spec, like CUE, Dhall or a series of
  small shell scripts you are more than welcome to.

*** Planned

- cdn -> if this attr exists and builds some set of static outputs
  then each of those gets uploaded to nais cdn and build outputs
  of the workflow aciton

- release -> We should have an ergonomic way of going from tag or
  somesuch to github release
